name = "citrus-tube"

[env.dev]
name="devdev"

[[d1_databases]]
binding = "DB"
database_name = "citrus-tube"
database_id = "dc9ccf0a-0d65-47e0-adda-e153620a021f"
preview_database_id = "DB"
migrations_dir = "drizzle/migrations"